### ISSUE TITLE
Добавить поддержку русского ГДЗ.

### ISSUE THREAD

**Issue by mishailovic** [Maks4816/gdz_ukraine#1]
Было бы неплохо добавить поддержку для русского ГДЗ, даже библиотека готовая есть: https://github.com/crinny/gdz
А так бот шикарный :3

**Comment by mishailovic** [comment]
Либо просто написать отдельного бота, чтобы у юзера не мешалось все в глазах.

**Comment by Maks4816** [comment]
Спасибо за ишью. Попробую написать всё в одном боте с помощью этой либы :)
